GET http://localhost:3003/api/comments/6302101bb807e34f1ab22a84
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXVlbCIsImlkIjoiNjJlMGZhYWJjOTJmYzM5MDgxMjJkYjE0IiwiaWF0IjoxNjY0OTc0Nzk1LCJleHAiOjE2NjQ5NzgzOTV9.zwIQ6BbeP_u0UIlT0B4xZO6VzjSkckGCd_XLeqacWCY
###
POST http://localhost:3003/api/comments
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNveWVsYW1pIiwiaWQiOiI2MmY2MDNlNDFhNzY2MjA5ZWI3ZjMzMWUiLCJpYXQiOjE2NjQwMTg0NjEsImV4cCI6MTY2NDAyMjA2MX0.dce6zO17z3HIxoFztxHQg4jlv3JH3iVwV9J4Pbx9wYk

{
    "comment": "the third comment on the Comment db",
    "ref_blog_id": "6302101bb807e34f1ab22a84"
}
###
POST http://localhost:3003/login
content-Type: application/json

{
    "username": "soyelami",
    "name": "oyelami",
    "password": "123456"
}
###
GET http://localhost:3003/api/comments
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNveWVsYW1pIiwiaWQiOiI2MmY2MDNlNDFhNzY2MjA5ZWI3ZjMzMWUiLCJpYXQiOjE2NjU2NDQ3MzAsImV4cCI6MTY2NTY0ODMzMH0.qX3qB5gn-jc9zkzGJf611BC9CSrDe4ap0gZJOKRUpe8
