GET http://localhost:3003/api/blogs/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXVlbCIsImlkIjoiNjJlMGZhYWJjOTJmYzM5MDgxMjJkYjE0IiwiaWF0IjoxNjU4OTQ1NTEzLCJleHAiOjE2NTg5NDczMTN9.FvLxOcTBpaKeRf87xREZk73cQgSGywATThf1xDMxdys
GET http://localhost:3003/api/blogs/62dc15c72f4cbd25acc04ee9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXVlbCIsImlkIjoiNjJlMGZhYWJjOTJmYzM5MDgxMjJkYjE0IiwiaWF0IjoxNjU4OTQ1NTEzLCJleHAiOjE2NTg5NDczMTN9.FvLxOcTBpaKeRf87xREZk73cQgSGywATThf1xDMxdys
POST http://localhost:3003/api/blogs/   HTTP/1.1
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXVlbCIsImlkIjoiNjJlMGZhYWJjOTJmYzM5MDgxMjJkYjE0IiwiaWF0IjoxNjU4OTQ1NTEzLCJleHAiOjE2NTg5NDczMTN9.FvLxOcTBpaKeRf87xREZk73cQgSGywATThf1xDMxdys
{
    "id": "5a422aa71b54a676234d17f8",
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": "5",
    "userId": "62e0faabc92fc3908122db14"
}
####
PUT http://localhost:3003/api/blogs/62dc0f2907c463f42e5e1d3b
content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": "22"
}
###
DELETE http://localhost:3003/api/blogs/62e0fafec92fc3908122db17 HTTP/1.1
####
POST http://localhost:3003/api/users
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXVlbCIsImlkIjoiNjJlMGZhYWJjOTJmYzM5MDgxMjJkYjE0IiwiaWF0IjoxNjU4OTQ1NTEzLCJleHAiOjE2NTg5NDczMTN9.FvLxOcTBpaKeRf87xREZk73cQgSGywATThf1xDMxdys
{
    "username": "damilare",
    "name": "oyelami",
    "password": "123456"
}
###
GET http://localhost:3003/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXVlbCIsImlkIjoiNjJlMGZhYWJjOTJmYzM5MDgxMjJkYjE0IiwiaWF0IjoxNjU4OTQ1NTEzLCJleHAiOjE2NTg5NDczMTN9.FvLxOcTBpaKeRf87xREZk73cQgSGywATThf1xDMxdys
###
POST http://localhost:3003/login
content-Type: application/json

{
    "username": "samuel",
    "name": "sammy",
    "password": "123456"
}