POST http://localhost:3003/login
content-Type: application/json

{
    "username": "samuel",
    "name": "sammy",
    "password": "123456"
}
###
POST https://blog-server-eta.vercel.app/login

{
    "username": "samuel",
    "name": "sammy",
    "password": "123456"
}